import { expect, test } from '@playwright/test';

const STUDIO = '/docs/studio/';

/**
 * The studio bundles eSpeak NG, which is 18 MB. These tests guard the two properties that
 * matter and are easy to break silently: that it is never fetched unless asked for, and
 * that anything it generates is marked as synthesized.
 */
test.describe('studio', () => {
  test('does not fetch the speech engine until someone asks for it', async ({ page }) => {
    const engineRequests: string[] = [];
    page.on('request', (request) => {
      if (request.url().includes('/vendor/espeak-ng')) engineRequests.push(request.url());
    });

    await page.goto(STUDIO);
    await expect(page.locator('.suggest').first()).toBeVisible();
    expect(engineRequests).toEqual([]);

    await page.locator('.suggest').first().click();
    await expect
      .poll(() => engineRequests.length, { timeout: 60_000 })
      .toBeGreaterThan(0);
  });

  test('suggesting from spelling fills the IPA and marks the result synthesized', async ({
    page,
  }) => {
    await page.goto(STUDIO);
    await page.locator('#name').fill('Jailson');
    await page.locator('.in-lang').first().fill('pt-BR');
    await page.locator('.suggest').first().click();

    await expect(page.locator('.rec-status').first()).toContainText('Generated by eSpeak', {
      timeout: 60_000,
    });

    // eSpeak's pt-BR reading of this name; asserted loosely so a version bump that shifts a
    // vowel does not fail the suite — the point is that real IPA arrived.
    await expect(page.locator('.in-ipa').first()).toHaveValue(/ʒ.*s/);

    // The honesty guarantee: generated audio is never left looking like a recording.
    await expect(page.locator('.in-synthetic').first()).toBeChecked();
    await expect(page.locator('#snippet')).toContainText('synthetic');
    await expect(page.locator('#preview say-my-name button').first()).toHaveAttribute(
      'aria-label',
      /synthesized voice/,
    );
  });

  test('derives the respelling from the IPA as it is typed', async ({ page }) => {
    await page.goto(STUDIO);
    const ipa = page.locator('.in-ipa').first();
    const respell = page.locator('.in-respell').first();

    await ipa.fill('maˈria');
    await expect(respell).toHaveValue('mah-REE-ah');

    await ipa.fill('ˈdʒon');
    await expect(respell).toHaveValue('john');
  });

  test('stops overwriting the respelling once it has been edited by hand', async ({ page }) => {
    await page.goto(STUDIO);
    const ipa = page.locator('.in-ipa').first();
    const respell = page.locator('.in-respell').first();

    await ipa.fill('maˈria');
    await expect(respell).toHaveValue('mah-REE-ah');

    // A considered choice outranks a generated one, permanently.
    await respell.fill('muh-REE-uh');
    await ipa.fill('ʒˌaˈiʊsoŋ');
    await expect(respell).toHaveValue('muh-REE-uh');
  });

  test('the generated take is playable and downloadable', async ({ page }) => {
    await page.goto(STUDIO);
    await page.locator('.suggest').first().click();
    await expect(page.locator('.rec-status').first()).toContainText('Generated by eSpeak', {
      timeout: 60_000,
    });

    await expect(page.locator('.play').first()).toBeEnabled();
    await expect(page.locator('.dl-wav').first()).toBeEnabled();
    await expect(page.locator('.wave').first()).toBeVisible();
  });
});
