import { expect, test, type Page } from '@playwright/test';

const STUDIO = '/docs/studio/';

/**
 * The studio's editing surface is the rendered widget itself: you click the name, the
 * respelling or the IPA where they appear. Anything the widget is not currently showing —
 * an empty field, or a display mode that hides it — gets a dashed chip below the stage
 * instead. These tests drive both, because that is all a visitor has.
 */
async function edit(page: Page, part: 'name' | 'respell' | 'ipa', value: string) {
  const ghost = page.locator(`.ghost-edit[data-edit="${part}"]`);
  if (part !== 'name' && (await ghost.isVisible())) {
    await ghost.click();
  } else {
    // Click low in the box: in ruby mode the respelling sits inside the name's own box,
    // and the centre of it is ambiguous.
    const box = await page.locator(`#preview [part~="${part}"]`).first().boundingBox();
    if (!box) throw new Error(`nothing to click for ${part}`);
    await page.mouse.click(box.x + box.width / 2, box.y + box.height - 6);
  }

  const LABELS = { name: 'Edit name', respell: 'Edit respelling', ipa: 'Edit IPA' };
  const editor = page.locator('input.inline-edit');
  // Guards the click landing on the wrong part — in ruby mode they overlap.
  await expect(editor).toHaveAttribute('aria-label', LABELS[part]);
  await editor.fill(value);
  await editor.press('Enter');
  await expect(editor).toHaveCount(0);
}

/** Geometry the page must hold to while an editor is open. */
async function layout(page: Page) {
  return page.evaluate(() => ({
    overflowing:
      document.documentElement.scrollWidth > document.documentElement.clientWidth,
    stageLeft: Math.round(document.querySelector('.stage')!.getBoundingClientRect().left),
    scrollX: Math.round(window.scrollX),
  }));
}

/**
 * The studio bundles eSpeak NG, which is 18 MB. These tests guard the two properties that
 * matter and are easy to break silently: that it is never fetched unless asked for, and
 * that anything it generates is marked as synthesized.
 */
test.describe('studio', () => {
  test('does not fetch the speech engine until someone asks for it', async ({ page }) => {
    const engineRequests: string[] = [];
    page.on('request', (request) => {
      if (request.url().includes('/vendor/espeak-ng')) engineRequests.push(request.url());
    });

    await page.goto(STUDIO);
    await expect(page.locator('.suggest').first()).toBeVisible();
    expect(engineRequests).toEqual([]);

    await page.locator('.suggest').first().click();
    await expect
      .poll(() => engineRequests.length, { timeout: 60_000 })
      .toBeGreaterThan(0);
  });

  test('speaking it fills the IPA and marks the result synthesized', async ({ page }) => {
    await page.goto(STUDIO);
    await edit(page, 'name', 'Jailson');
    await page.locator('.in-lang').first().fill('pt-BR');
    await page.locator('.suggest').first().click();

    await expect(page.locator('.rec-status').first()).toContainText('Generated by eSpeak', {
      timeout: 60_000,
    });

    // eSpeak's pt-BR reading of this name; asserted loosely so a version bump that shifts a
    // vowel does not fail the suite — the point is that real IPA arrived.
    await expect(page.locator('.in-ipa').first()).toHaveValue(/ʒ.*s/);

    // The honesty guarantee: generated audio is never left looking like a recording.
    await expect(page.locator('.in-synthetic').first()).toBeChecked();
    await expect(page.locator('#snippet')).toContainText('synthetic');
    await expect(page.locator('#preview say-my-name button').first()).toHaveAttribute(
      'aria-label',
      /synthesized voice/,
    );
  });

  test('opening an editor does not disturb the page around it', async ({ page }) => {
    // The editor is an absolutely positioned text input on the body, which makes it an
    // easy thing to break: inheriting a percentage width, or being anchored past the
    // right edge, widens the document and slides the whole layout sideways.
    await page.goto(STUDIO);
    await edit(page, 'ipa', 'maˈria');
    const before = await layout(page);
    expect(before.overflowing).toBe(false);

    for (const part of ['name', 'respell', 'ipa'] as const) {
      const box = await page.locator(`#preview [part~="${part}"]`).first().boundingBox();
      if (!box) throw new Error(`nothing to click for ${part}`);
      await page.mouse.click(box.x + box.width / 2, box.y + box.height - 6);
      await expect(page.locator('input.inline-edit')).toBeVisible();

      const during = await layout(page);
      expect(during, `layout moved while editing the ${part}`).toEqual(before);

      // ...and the editor itself has to stay on screen to be usable.
      const editor = await page.locator('input.inline-edit').boundingBox();
      const width = page.viewportSize()!.width;
      expect(editor!.x).toBeGreaterThanOrEqual(0);
      expect(editor!.x + editor!.width).toBeLessThanOrEqual(width);

      await page.locator('input.inline-edit').press('Escape');
      await expect(page.locator('input.inline-edit')).toHaveCount(0);
    }

    expect(await layout(page)).toEqual(before);
  });

  test('editing the name on the stage changes the widget', async ({ page }) => {
    await page.goto(STUDIO);
    await edit(page, 'name', 'Beatriz');

    await expect(page.locator('#preview say-my-name')).toContainText('Beatriz');
    await expect(page.locator('#snippet')).toContainText('>Beatriz<');
  });

  test('derives the respelling from the IPA as it is typed', async ({ page }) => {
    await page.goto(STUDIO);
    const respell = page.locator('.in-respell');

    // Nothing to click yet, so the chip is the way in.
    await edit(page, 'ipa', 'maˈria');
    await expect(respell).toHaveValue('mah-REE-ah');
    await expect(page.locator('#preview [part~="respell"]')).toHaveText('mah-REE-ah');

    // Now it is on the stage, and clicking it there works.
    await edit(page, 'ipa', 'ˈdʒon');
    await expect(respell).toHaveValue('john');
  });

  test('stops overwriting the respelling once it has been edited by hand', async ({ page }) => {
    await page.goto(STUDIO);
    const respell = page.locator('.in-respell');

    await edit(page, 'ipa', 'maˈria');
    await expect(respell).toHaveValue('mah-REE-ah');

    // A considered choice outranks a generated one, permanently.
    await edit(page, 'respell', 'muh-REE-uh');
    await edit(page, 'ipa', 'ʒˌaˈiʊsoŋ');
    await expect(respell).toHaveValue('muh-REE-uh');
  });

  test('keeps both written forms reachable when the widget hides them', async ({ page }) => {
    await page.goto(STUDIO);
    await edit(page, 'ipa', 'maˈria');

    // "just the button" renders no phonetics at all — the chips have to take over.
    await page.locator('.chip[data-display="none"]').click();
    await expect(page.locator('#preview [part~="ipa"]')).toHaveCount(0);
    await expect(page.locator('.ghost-edit[data-edit="ipa"]')).toBeVisible();
    await expect(page.locator('.ghost-edit[data-edit="respell"]')).toBeVisible();

    await edit(page, 'ipa', 'ˈdʒon');
    await expect(page.locator('.in-ipa')).toHaveValue('ˈdʒon');
  });

  test('fills both fields from the name and language as you type', async ({ page }) => {
    // No button press: this is the whole point of the studio.
    await page.goto(STUDIO);
    await page.locator('.in-lang').first().fill('pt-BR');
    await edit(page, 'name', 'Beatriz');

    await expect(page.locator('.in-ipa').first()).toHaveValue(/\S/, { timeout: 90_000 });
    await expect(page.locator('.in-respell').first()).toHaveValue(/\S/);
  });

  test('refills automatically once the engine is loaded', async ({ page }) => {
    await page.goto(STUDIO);
    await page.locator('.in-lang').first().fill('pt-BR');
    await page.locator('.suggest').first().click();
    await expect(page.locator('.rec-status').first()).toContainText('Generated by eSpeak', {
      timeout: 60_000,
    });

    // Changing the language alone re-derives both fields, no second press.
    await page.locator('.in-lang').first().fill('en-US');
    await expect(page.locator('.in-ipa').first()).toHaveValue(/dʒ/, { timeout: 30_000 });
    await expect(page.locator('.in-respell').first()).toHaveValue(/^J/);
  });

  test('leaves hand-written IPA alone when the language changes', async ({ page }) => {
    await page.goto(STUDIO);
    await page.locator('.suggest').first().click();
    await expect(page.locator('.rec-status').first()).toContainText('Generated by eSpeak', {
      timeout: 60_000,
    });

    await edit(page, 'ipa', 'ʒaˈiwsõ');
    await page.locator('.in-lang').first().fill('pt-BR');
    await page.waitForTimeout(1500);
    await expect(page.locator('.in-ipa').first()).toHaveValue('ʒaˈiwsõ');
  });

  test('the generated take is playable and downloadable', async ({ page }) => {
    await page.goto(STUDIO);
    await page.locator('.suggest').first().click();
    await expect(page.locator('.rec-status').first()).toContainText('Generated by eSpeak', {
      timeout: 60_000,
    });

    await expect(page.locator('.play').first()).toBeEnabled();
    await expect(page.locator('.dl-wav').first()).toBeEnabled();
    await expect(page.locator('.wave').first()).toBeVisible();
  });
});
