/**
 * Generate the studio's language list from the engine itself.
 *
 * Asking eSpeak what it supports beats hand-maintaining a list: it cannot drift, and a
 * version bump updates it for free. Language codes and names are facts about the engine,
 * not a derivative of its source, so the generated file carries no licence weight.
 */
import ESpeakNg from 'espeak-ng';
import { mkdir, writeFile } from 'node:fs/promises';

/** `pt-br` reads oddly in a `lang` attribute; BCP 47 wants `pt-BR`. */
function toBcp47(code) {
  const [primary, ...rest] = code.split('-');
  return [
    primary.toLowerCase(),
    ...rest.map((part) => (/^[a-z]{2}$/i.test(part) ? part.toUpperCase() : part)),
  ].join('-');
}

export async function listVoices() {
  let output = '';
  await ESpeakNg({
    arguments: ['--voices'],
    print: (line) => {
      output += `${line}\n`;
    },
    printErr: () => {},
  });

  return output
    .trim()
    .split('\n')
    .slice(1) // column headings
    .map((line) => {
      // Pty | Language | Age/Gender | VoiceName | File | Other Languages
      const columns = line.trim().split(/\s+/);
      const code = columns[1];
      const name = columns[3]?.replace(/_/g, ' ');
      return code && name ? { code: toBcp47(code), name } : null;
    })
    .filter(Boolean)
    .sort((a, b) => a.name.localeCompare(b.name));
}

export async function writeVoices(target = 'docs/studio/vendor/voices.js') {
  const voices = await listVoices();
  await mkdir(target.replace(/\/[^/]+$/, ''), { recursive: true });
  await writeFile(
    target,
    `// Generated by scripts/voices.mjs from the bundled eSpeak NG. Do not edit.\n` +
      `export const VOICES = ${JSON.stringify(voices, null, 0)};\n`,
    'utf8',
  );
  return voices.length;
}
